---

- name: Create Git Repo Root
  sudo: "{{ user_name }}"
  file: dest=~/gitroot mode=755 owner={{ user_name }} group={{ user_name }} state=directory

- name: Check for /var/www
  stat: path=/var/www
  register: www

- name: Deactivate existing /var/www
  sudo: True
  command: mv /var/www /var/www.old
  when: www.stat.exists

- name: Assure /var/www exists
  sudo: True
  file: path=/var/www state=directory owner={{ user_name }} group={{ user_name }} state=directory

- name: Create symlink to /var/www from the deployment www environment
  sudo: True
  file: src=/home/{{ user_name }}/gitroot/pancancer.info.content/www dest=/var/www state=link
  




